export const PERMISSIONS = {
  ASSET_VIEW: 'ASSET_VIEW',
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_EDIT: 'ASSET_EDIT',
  ASSET_DELETE: 'ASSET_DELETE',
  WORKORDER_VIEW: 'WORKORDER_VIEW',
  WORKORDER_CREATE: 'WORKORDER_CREATE',
  WORKORDER_EDIT: 'WORKORDER_EDIT',
  WORKORDER_DELETE: 'WORKORDER_DELETE',
  MAINTENANCE_VIEW: 'MAINTENANCE_VIEW',
  MAINTENANCE_CREATE: 'MAINTENANCE_CREATE',
  MAINTENANCE_EDIT: 'MAINTENANCE_EDIT',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_EDIT: 'INVENTORY_EDIT',
  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_EDIT: 'PURCHASE_EDIT',
  VENDOR_VIEW: 'VENDOR_VIEW',
  VENDOR_CREATE: 'VENDOR_CREATE',
  VENDOR_EDIT: 'VENDOR_EDIT',
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_DELETE: 'USER_DELETE',
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  REPORT_VIEW: 'REPORT_VIEW'
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

/**
 * Role-to-permission mapping.
 */
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.WORKORDER_VIEW, PERMISSIONS.WORKORDER_CREATE, PERMISSIONS.WORKORDER_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_EDIT,
    PERMISSIONS.VENDOR_VIEW, PERMISSIONS.VENDOR_CREATE, PERMISSIONS.VENDOR_EDIT,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_VIEW
  ],
  USER: [
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.WORKORDER_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD
  ]
}
