import type { UserRole } from '@/shared/types/user.types'

export const PERMISSIONS = {
  // Assets
  ASSET_VIEW: 'ASSET_VIEW',
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_EDIT: 'ASSET_EDIT',
  ASSET_DELETE: 'ASSET_DELETE',

  // Assignments
  ASSIGNMENT_VIEW: 'ASSIGNMENT_VIEW',
  ASSIGNMENT_CREATE: 'ASSIGNMENT_CREATE',
  ASSIGNMENT_RETURN: 'ASSIGNMENT_RETURN',

  // Work Orders
  WORKORDER_VIEW: 'WORKORDER_VIEW',
  WORKORDER_CREATE: 'WORKORDER_CREATE',
  WORKORDER_EDIT: 'WORKORDER_EDIT',
  WORKORDER_DELETE: 'WORKORDER_DELETE',

  // Maintenance
  MAINTENANCE_VIEW: 'MAINTENANCE_VIEW',
  MAINTENANCE_CREATE: 'MAINTENANCE_CREATE',
  MAINTENANCE_EDIT: 'MAINTENANCE_EDIT',
  MAINTENANCE_DELETE: 'MAINTENANCE_DELETE',

  // Inventory
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_EDIT: 'INVENTORY_EDIT',
  INVENTORY_DELETE: 'INVENTORY_DELETE',

  // Purchase Orders
  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_EDIT: 'PURCHASE_EDIT',
  PURCHASE_DELETE: 'PURCHASE_DELETE',

  // Vendors
  VENDOR_VIEW: 'VENDOR_VIEW',
  VENDOR_CREATE: 'VENDOR_CREATE',
  VENDOR_EDIT: 'VENDOR_EDIT',
  VENDOR_DELETE: 'VENDOR_DELETE',

  // Users
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_DELETE: 'USER_DELETE',

  // Departments & Locations
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_EDIT: 'DEPARTMENT_EDIT',
  LOCATION_VIEW: 'LOCATION_VIEW',
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_EDIT: 'LOCATION_EDIT',

  // Notifications
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',

  // Documents
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',

  // Audit & Reports
  AUDIT_VIEW: 'AUDIT_VIEW',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT'
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

/**
 * Role-to-permission mapping.
 * ADMIN gets everything. MANAGER gets operational access. USER gets read-only + own items.
 */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),

  MANAGER: [
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSIGNMENT_VIEW, PERMISSIONS.ASSIGNMENT_CREATE, PERMISSIONS.ASSIGNMENT_RETURN,
    PERMISSIONS.WORKORDER_VIEW, PERMISSIONS.WORKORDER_CREATE, PERMISSIONS.WORKORDER_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_EDIT,
    PERMISSIONS.VENDOR_VIEW, PERMISSIONS.VENDOR_CREATE, PERMISSIONS.VENDOR_EDIT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW, PERMISSIONS.DEPARTMENT_CREATE, PERMISSIONS.DEPARTMENT_EDIT,
    PERMISSIONS.LOCATION_VIEW, PERMISSIONS.LOCATION_CREATE, PERMISSIONS.LOCATION_EDIT,
    PERMISSIONS.NOTIFICATION_VIEW, PERMISSIONS.NOTIFICATION_CREATE,
    PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT
  ],

  USER: [
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.WORKORDER_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.LOCATION_VIEW
  ]
}
