spring.application.name=enterprise-asset-management

server.port=8080

# =========================
# PostgreSQL
# =========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/enterprise_asset_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
logging.level.org.flywaydb=DEBUG

# =========================
# JWT Settings
# =========================
jwt.secret=${JWT_SECRET:MzRjYjVkNmU3YzhhOWI0ZTEwZjJhM2M1ZTZiN2Q4ZTkxMGExMmIzYzRkNWU2ZjdhOGI5YzBkMWUyZjNhNGI1Yw==}
jwt.expiration=24h

# =========================
# File Storage
# =========================
eams.storage.local.path=${STORAGE_PATH:./uploads}

# =========================
# Multipart Upload
# =========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB